### ISSUE TITLE
Cambio en informe

### ISSUE THREAD

**Issue by lautaroalvarez** [araml/SSOO#10]
Para que se arme el índice hay que cambiar el \section*{Ejercicio X} por \section{Ejercicio X}. No se los quise cambiar para que no haya drama de merge con el git.

No tengo la fuente y no la pude incluir bien, si la tienen y la pueden agregar al git para compilarlo genial, sino yo lo probé sin esa fuente y no hay drama. Compilelo alguno de ustedes y genial.

@araml @abeldelgadillo

**Comment by araml** [comment]
que fuente?

**Comment by lautaroalvarez** [comment]
\usepackage{charter}

igual para compilar lo comenté, mientras que después lo compile otro no hay drama.

**Comment by araml** [comment]
Dale yo lo mando.
