### ISSUE TITLE
Parámetros de compilación

### ISSUE THREAD

**Issue by lautaroalvarez** [araml/SSOO#9]
En mi computadora tira error con **-std=c++14**. Me pasó lo mismo compilando desde una computadora del laboratorio. Hay que ver esto, porque tiene que compilar en el labo para que lo corrigan.

**Comment by lautaroalvarez** [comment]
pensé que podía asignarselo a todos pero buen

**Comment by araml** [comment]
Que versión de gcc tenés?. Ahi lo cambié -std=c++11, estoy casi seguro que ahora deberia funcionar en los labos. 

btw podes quotear con @nombre.

**Comment by lautaroalvarez** [comment]
mas que nada que ande en el labo, para que no nos puedan decir nada.. en un rato si puedo lo pruebo

**Comment by araml** [comment]
Ok. Mañana lo veo en los labos.
